### ISSUE TITLE
Open Tiff launch an exception "Old-style JPEG compression support is not configured. `' @ error/tiff.c/TIFFErrors/656"

### ISSUE THREAD

**Issue by josecarvalho2** [dlemstra/Magick.NET#441]
### Prerequisites

- [x] I have written a descriptive issue title
- [X ] I have verified that I am using the latest version of Magick.NET
- [ ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Open tiff file launch an exception "Old-style JPEG compression support is not configured. `' @ error/tiff.c/TIFFErrors/656"

### Steps to Reproduce
Attachment includes a sample
---
            System.IO.FileStream    fsSource = null;
            System.IO.FileStream    fsDest = null;
            ImageMagick.MagickImageCollection collImageMag = null;

            try
            {
                this.Cursor = System.Windows.Forms.Cursors.WaitCursor;

                System.DateTime dtBegin;
                dtBegin = System.DateTime.Now;

                string strSourcePathFileName;
                strSourcePathFileName = textBoxSourceFileName.Text;

                string  strSourceFileName;
                strSourceFileName = System.IO.Path.GetFileName(strSourcePathFileName);

                string strSourceExt;
                strSourceExt = System.IO.Path.GetExtension(strSourceFileName);

                string strDestFileName;
                strDestFileName = Papiro.platform.io.Path.FileNameReplaceExt(strSourceFileName, ".pdf");

                string strDestPathFileName;
                strDestPathFileName = textBoxDestPath.Text + System.IO.Path.DirectorySeparatorChar + strDestFileName;

                fsSource = new System.IO.FileStream(strSourcePathFileName, System.IO.FileMode.Open, System.IO.FileAccess.Read);

                ImageMagick.MagickReadSettings imageMagReadSettings;
                imageMagReadSettings = new ImageMagick.MagickReadSettings();
                imageMagReadSettings.SetDefine(ImageMagick.MagickFormat.Tif, "ignore-tags", "32931,32934,59932");
                imageMagReadSettings.SetDefine(ImageMagick.MagickFormat.Tif, "ignore-layers", true);

imageMagReadSettings);
                collImageMag = new ImageMagick.MagickImageCollection();
                collImageMag.AddRange(fsSource, imageMagReadSettings);

                fsDest = new System.IO.FileStream(strDestPathFileName, System.IO.FileMode.CreateNew, System.IO.FileAccess.Write);

                int     nPage = 1;  // nPage start at 1 to normal page numbering

                foreach ( ImageMagick.MagickImage itImage in collImageMag )
                {
                    if ( ((itImage.Format == ImageMagick.MagickFormat.Tif) || (itImage.Format == ImageMagick.MagickFormat.Tiff) || (itImage.Format == ImageMagick.MagickFormat.Tiff64)) &&
                            (itImage.ColorType != ImageMagick.ColorType.Bilevel) )
                    {
                        itImage.Settings.Compression = ImageMagick.CompressionMethod.JPEG;
                    }
                    itImage.Quality = 10;

                    nPage++;
                }

                collImageMag.Write(fsDest, ImageMagick.MagickFormat.Pdf);

                collImageMag.Dispose();
                collImageMag = null;

                fsDest.Close();
                fsDest = null;
                fsSource.Close();
                fsSource = null;

                System.DateTime dtEnd;
                dtEnd = System.DateTime.Now;

                this.Cursor = System.Windows.Forms.Cursors.Default;
                System.Windows.Forms.MessageBox.Show("Acabou! Demorei: " + dtEnd.Subtract(dtBegin).TotalSeconds + " segundos", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch ( ImageMagick.MagickException exMagick )
            {
                if ( collImageMag != null )
                    collImageMag.Dispose();
                if ( fsDest != null )
                    fsDest.Close();
                if ( fsSource != null )
                    fsSource.Close();
                this.Cursor = System.Windows.Forms.Cursors.Default;
                System.Windows.Forms.MessageBox.Show(exMagick.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch ( System.Exception ex )
            {
                if ( collImageMag != null )
                    collImageMag.Dispose();
                if ( fsDest != null )
                    fsDest.Close();
                if ( fsSource != null )
                    fsSource.Close();
                this.Cursor = System.Windows.Forms.Cursors.Default;
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }

---

### System Configuration
Windows Server 2008 R2, VS 2015

- Magick.NET version: 7.13
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
It appears the libtiff is currently build without support for OJPEG compression. I just pushed a patch to the ImageMagick respository to enable this. You will be able to read the file in the next release of Magick.NET

**Comment by josecarvalho2** [comment]
Can you delete the zip attachment, as it contains personal data?
Thanks

**Comment by dlemstra** [comment]
I cannot remove it myself but you can edit your initial message and remove the link to the file. If you want it removed from the GitHub server you will need to contact support: https://github.com/contact.

**Comment by josecarvalho2** [comment]
I have tried again with 7.13.1, but the error stills the same. I have also tried with libtiff and it works fine. Is it necessary to active any falg? Something with native? I am using AnyCPU.

**Comment by dlemstra** [comment]
It appears I made a mistake when rebuilding ImageMagick. It was using an older version of the tiff library for Windows. I am now working on completely changing the Native library so it might take a while before the new release will be published.
